spring:
  application:
    name: PresentationGen_Back_End
    #数据库链接信息
  datasource:
    url: jdbc:mysql://localhost:3306/pgen
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    async:
      #异步请求最长等待时间
      request-timeout: 90000
  #文件上传大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

#文心一言配置
ernie:
  appKey: ?????????????????????????
  secretKey: ?????????????????????????
  accessTokenURL: https://aip.baidubce.com/oauth/2.0/token
  botURL: https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/ernie-3.5-8k-0205

#阿里云oss配置
aliyun:
  sms:
    keyID: ?????????????????????????
    keySecret: ?????????????????????????
    endpoint: ?????????????????????????
  oss:
    endpoint: ?????????????????????????
    accessKeyId: ?????????????????????????
    accessKeySecret: ?????????????????????????
    bucketName: pgen

# 设置全局路径Windows
path:
  templates:
    ppt: ../data/templates/cover/
    chap: ../data/templates/chap/
  markdown: ../data/markdown/
  record: ../data/record/

#设置全局路径Linux
#path:
#  templates:
#    ppt: /root/data/templates/cover/
#    chap: /root/data/templates/chap/
#  markdown: /root/data/markdown/
#  record: /root/data/record/

JWTSetting:
  signingKey: ?????????????????????????

